# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 421, 661))
        self.backgroundLabel.setText("")
        self.backgroundLabel.setPixmap(QtGui.QPixmap("HlpKYq.png"))
        self.backgroundLabel.setScaledContents(True)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.butonMic = QtWidgets.QPushButton(self.centralwidget)
        self.butonMic.setGeometry(QtCore.QRect(170, 570, 61, 61))
        self.butonMic.setStyleSheet("QPushButton{\n"
"    border-radius: 25px;\n"
"    border : 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: lightwhite;\n"
"\n"
"}")
        self.butonMic.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mic (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butonMic.setIcon(icon)
        self.butonMic.setIconSize(QtCore.QSize(40, 40))
        self.butonMic.setObjectName("butonMic")
        self.textBackgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.textBackgroundLabel.setGeometry(QtCore.QRect(20, 100, 371, 401))
        self.textBackgroundLabel.setStyleSheet("border-radius: 25px;\n"
"")
        self.textBackgroundLabel.setText("")
        self.textBackgroundLabel.setObjectName("textBackgroundLabel")
        self.micLabel = QtWidgets.QLabel(self.centralwidget)
        self.micLabel.setGeometry(QtCore.QRect(120, 140, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.micLabel.setFont(font)
        self.micLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.micLabel.setStyleSheet("background-color: rgb(3, 23, 34);\n"
"border-radius: 10px; color:white; padding:5px;")
        self.micLabel.setTextFormat(QtCore.Qt.RichText)
        self.micLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.micLabel.setWordWrap(True)
        self.micLabel.setIndent(1)
        self.micLabel.setObjectName("micLabel")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 421, 41))
        self.titleLabel.setStyleSheet("background-color: rgb(3, 20, 31);\n"
"")
        self.titleLabel.setText("")
        self.titleLabel.setObjectName("titleLabel")
        self.resultLebel = QtWidgets.QLabel(self.centralwidget)
        self.resultLebel.setGeometry(QtCore.QRect(30, 310, 281, 211))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.resultLebel.setFont(font)
        self.resultLebel.setStyleSheet("background-color: rgb(3, 23, 34);\n"
"border-radius: 10px; color:white; padding:5px;")
        self.resultLebel.setTextFormat(QtCore.Qt.RichText)
        self.resultLebel.setScaledContents(False)
        self.resultLebel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.resultLebel.setWordWrap(True)
        self.resultLebel.setIndent(1)
        self.resultLebel.setObjectName("resultLebel")
        self.minimizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.minimizeButton.setGeometry(QtCore.QRect(350, 10, 21, 21))
        self.minimizeButton.setStyleSheet("border-radius: 10px;\n"
"border : 2px solid rgba(222,159,52,255);\n"
"")
        self.minimizeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon1)
        self.minimizeButton.setIconSize(QtCore.QSize(23, 23))
        self.minimizeButton.setObjectName("minimizeButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(380, 10, 21, 21))
        self.closeButton.setStyleSheet("\n"
"border-radius: 10px;\n"
"border : 2px solid #df4744;\n"
"")
        self.closeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setIconSize(QtCore.QSize(23, 25))
        self.closeButton.setObjectName("closeButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setPixmap(QtGui.QPixmap("assistant.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setPixmap(QtGui.QPixmap("conversation.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(60, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        self.nameLabel.setFont(font)
        self.nameLabel.setTextFormat(QtCore.Qt.RichText)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLabel.setText("")
        self.nameLabel.setStyleSheet("color:white")
        self.sideBarButton = QtWidgets.QPushButton(self.centralwidget)
        self.sideBarButton.setGeometry(QtCore.QRect(10, 10, 21, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideBarButton.sizePolicy().hasHeightForWidth())
        self.sideBarButton.setSizePolicy(sizePolicy)
        self.sideBarButton.setStyleSheet("border-radius: 10px;\n"
"border :solid;")
        self.sideBarButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sideBarButton.setIcon(icon3)
        self.sideBarButton.setObjectName("sideBarButton")
        self.sideBarLabel = QtWidgets.QLabel(self.centralwidget)
        self.sideBarLabel.setGeometry(QtCore.QRect(0, 41, 231, 621))
        self.sideBarLabel.setStyleSheet("background-color:  rgb(3, 20, 31);\n"
"")
        self.sideBarLabel.setText("")
        self.sideBarLabel.setObjectName("sideBarLabel")
        self.gifLabel = QtWidgets.QLabel(self.centralwidget)
        self.gifLabel.setGeometry(QtCore.QRect(20, 70, 181, 151))
        self.gifLabel.setText("")
        self.gifLabel.setObjectName("gifLabel")
        self.sideHiddenButton = QtWidgets.QPushButton(self.centralwidget)
        self.sideHiddenButton.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.sideHiddenButton.setStyleSheet("border-radius: 10px;\n"
"border :solid;")
        self.sideHiddenButton.setText("")
        self.sideHiddenButton.setIcon(icon3)
        self.sideHiddenButton.setObjectName("sideHiddenButton")
        self.informationLabel = QtWidgets.QLabel(self.centralwidget)
        self.informationLabel.setGeometry(QtCore.QRect(20, 230, 181, 401))
        self.informationLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.informationLabel.setWordWrap(True)
        self.informationLabel.setObjectName("informationLabel")
        self.informationLabel.setStyleSheet("padding:2px; color:gray;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.micLabel.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.resultLebel.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.informationLabel.setText("<html><head/><body><br>Hello, I am Emily/Bumblebee, I am your voice assistant I am ready to perform my 24/7 functions at your request...<br><br><br><br><br>Created by:<br><br>MUSTAFA BAYBARS KESKİN<br>İLKİN KİRAZ<br>KAZIM İNCEBAY<br><br><br><br><p><em>version 1.0</em></p></body></html>")
        self.nameLabel.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
